server:
    port: 9090
logging:
    file.name: "simple.log"
spring:
  application:
    name: "spring-form-scratch"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    # username: postgres
    # password: ${SPRING_DATASOURCE_PASSWORD}
    # driver-class-name: org.postgresql.Driver
    # url: postgresql://${username}:${password}@db.lnteqanzilawnzembmyn.supabase.co:5432/postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates
    suffix: .html
  devtools:
    restart:
      enabled: true ## dev only!!!