server:
    port: 9090
logging:
    file.name: "simple.log"
spring:
  application:
    name: "spring-form-scratch"
  datasource:
    username: postgres
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: postgresql://${username}:${password}@db.lnteqanzilawnzembmyn.supabase.co:5432/postgres
#    url: jdbc:h2:file:/data/demo
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  #    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
